server.port=8090
spring.datasource.url=jdbc:mysql://localhost:3306/LevelUp
spring.datasource.username=root
spring.datasource.password=123esba09
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=false